### ISSUE TITLE
Update winston-fast-rabbitmq to v2.2.0

### ISSUE THREAD

**Issue by JimiC** [Qwant/Instant-Answers#30]
I strongly suggest updating `winston-fast-rabbitmq` to `v2.2.0` in order to resolve an issue with `rabbit-chatter` that leaves open connections. The issue is a serious one as it can lead to the inability to connect to the server after some time.

**Comment by stephanembl** [comment]
Hi! Thanks for the info, we will update it in next week's fixes along with other packages that need updating :)

**Comment by stephanembl** [comment]
fixed in #40
