### ISSUE TITLE
double-quote (") in query gives an error

### ISSUE THREAD

**Issue by myrosblog** [Qwant/Instant-Answers#33]
Hi,

I'm working on JSON/XML validator/beautifier but if you have a double quote in the query, it messes everything up :

For example, the query `md5 "abc"` :

<img width="684" alt="capture d ecran 2017-10-18 a 13 36 53" src="https://user-images.githubusercontent.com/9380369/31716734-7769ebf0-b409-11e7-8db9-98d2d250faf7.png">
check the url `?q=md5+"abc"` but there's nothing in the result div

it's because " has to be stripped here I guess :
<img width="550" alt="capture d ecran 2017-10-18 a 13 38 16" src="https://user-images.githubusercontent.com/9380369/31716780-a173b03e-b409-11e7-9998-6e5d05261c11.png">

**Comment by stephanembl** [comment]
Thank you for reporting that. This is an issue we only have in the sandbox, not on the production website. It will be fixed soon. Thanks again!

**Comment by myrosblog** [comment]
as a short term fix, replacing `[[=` by `[[!` in node_modules/@qwant/ia_sandbox/views/index.dot works
