### ISSUE TITLE
How to add a frontend framework (jquery, angular..) ?

### ISSUE THREAD

**Issue by myrosblog** [Qwant/Instant-Answers#34]
Hi,

I would like to know if it's possible to add a frontend framework ?

I tried to add in the template
```html
<!-- public/my_ia.dot -->
<script src="javascript/angular.js"></script>
```
with angular.js downloaded in `javascript/` folder (because direct link CDN are not working src="https://cdn.com" becomes src="localhost...https://cdn.com")

and in the front JS file :
```javascript
// public/javascript/my_ia.js
Icons.prototype.run = function() {
        var app = angular.module('app', []);
    };
```

but it's not working

any idea ?

thanks

**Comment by stephanembl** [comment]
Hi,

It is not possible to add a frontend framework. Surely it could be done using some tricks but we wouldn't accept a Pull Request containing such changes.

What are you trying to achieve?

**Comment by myrosblog** [comment]
Ok no problem

it would be nice to have jQuery for its shorthand functions

I'm working on the JS/XML beautifier :
<img width="1024" alt="capture d ecran 2017-10-19 a 21 32 49" src="https://user-images.githubusercontent.com/9380369/31790281-3d6f0176-b515-11e7-9f1e-10ad032dfe7c.png">

so the +/- icons should fold/unfold the section. It's easier with a framework
