### ISSUE TITLE
[new IA] IA-EXODUS_PRIVACY

### ISSUE THREAD

**Issue by BillCarsonFr** [Qwant/Instant-Answers#42]
What about a new IA using Exodus Privacy that would answer with a quick preview of the EP report when entering the name/id of an android app?
Would you be interested by such an IA? I have been working on https://www.producthunt.com/posts/exodify another tool using EP API.

**Comment by stephanembl** [comment]
Hi @BillCarsonFr!

While developing an Exodus Privacy IA is not our top priority right now, we did think about it... we have some ideas but we still need to think about some essential stuff (integration, triggering, some sort of scoring system...) and also, work it in our (very busy) roadmap :)

If you or someone else want(s) to take a go at it, please do! And keep us posted :) Thank you!
