### ISSUE TITLE
[CONTRIB Calculator] Base conversion tool

### ISSUE THREAD

**Issue by fiksd** [Qwant/Instant-Answers#45]
Hello,

I just discovered this project and thought this could be a good opportunity to make a first contribution to an open-source project. So I picked something from the idea pool and started working on a base conversion tool for the calculator.

Here is what I've got so far:
![screen1](https://user-images.githubusercontent.com/34415433/40840769-951564f0-6597-11e8-9348-f9e4d2165ada.png)
![screen2](https://user-images.githubusercontent.com/34415433/40840789-a059e976-6597-11e8-9ae8-3d5b5af37e7c.png)

Some minor improvements could still be made, such as adding support for decimal numbers.

Maybe you would be interested?
Thanks

**Comment by stephanembl** [comment]
Hi @fiksd ! I apologize for the late answer, we have so much on our hands right now at Qwant :)

We do appreciate your contribution! Kudos for picking our project to make your first contribution! Can you make a pull request with your work? We'll take it from there!

**Comment by fiksd** [comment]
It's done :)
#47
