### ISSUE TITLE
Update design to match new layout

### ISSUE THREAD

**Issue by Foorack** [Qwant/Instant-Answers#48]

**Comment by stephanembl** [comment]
We will in an upcoming update :)

**Comment by Foorack** [comment]
Any status update? :slightly_smiling_face: 

Please re-open this until the issue is done.

**Comment by stephanembl** [comment]
Hey @Foorack :) We closed the issue as it wasn't really an issue!

But... We just released Instant Answers 4.0.0 which bundles the new design (minus the dark theme for now). :)

Feel free to read the doc as some things changed drastically. Enjoy!

**Comment by Foorack** [comment]
@stephanemombuleau Ah, thank you! :smiley: :tada:
