### ISSUE TITLE
CSS file not generated and always overridden

### ISSUE THREAD

**Issue by ddsky** [Qwant/Instant-Answers#49]
Following the tutorial at step [5.1](https://github.com/Qwant/Instant-Answers/wiki/5.1.-Tutorial-1---Random-generator) - I run into a problem at ``grunt && npm start`` which does not start and aborts due to a warning ``Running "dot-generate" task
Warning: Unable to read "src\modules\random_generator\public\css\random_generator.css" file (Error code: ENOENT). Use --force to continue.``

Also creating the CSS manually does not work and gets deleted automatically every time I run the command.

I could do ``grunt --force && npm start`` which works in that step but the problem comes again when I try to run ``npm run sandbox``.

**Comment by stephanembl** [comment]
Hi @ddsky !

We've moved on to SASS files, but forgot to update the IA generator. We have a big update that we're going to ship this summer that will fix that.

In the meantime, to fix this yourself, you have to create a `your_ia_name.scss` file in the public\css\ folder of your IA. The grunt task will generate a .css file out of this .scss file. You can write either [SASS](http://sass-lang.com/guide) or CSS in the .scss file. 

Happy hacking!

**Comment by ddsky** [comment]
Thank you @stephanemombuleau that solved that issue!

**Comment by stephanembl** [comment]
Glad it helped :)
