### ISSUE TITLE
Bangs like DuckDuckGo

### ISSUE THREAD

**Issue by ghost** [Qwant/Instant-Answers#52]
Hello,

Is this the right place to implement [bangs like DuckDuckGo has](https://duckduckgo.com/bang) e.g !steam to search on steam or !g to search on google?

**Comment by alexisvigoureux** [comment]
Hello @LoveIsGrief ,

We have a special page where you can see and submit your own Qwick search shortcuts => https://help.qwant.com/help/qwant-search/searching/how-use-qwick/

**Comment by ghost** [comment]
That answered my question, thank you!
