### ISSUE TITLE
Remove MyIp from the idea list

### ISSUE THREAD

**Issue by northvik** [Qwant/Instant-Answers#63]
Hi,
So I notice that you are listing the `My ip` in the Instant answers list of idea.
Someone try to do it, https://github.com/Qwant/Instant-Answers/pull/36 and the PR was closed because: 

> We don't keep any info about our users. We don't want to give the impression that we use their IP address.

Which is a great reason but in this case maybe you shouldn't propose it as an idea.
I would have create a PR on the Wiki to remove it, but I didn't found a way to do it, sorry.
Thank's for your great search engine, continue the good work :1st_place_medal:

**Comment by stephanembl** [comment]
Hi!
Good point :D I don't think Github handles pull requests on wiki pages unfortunately, but we will remove it ourselves :)
Thanks for the support and kind words! :D 

PS: I've seen that you've contacted us through our contact form. Just so you know, creating an issue for technical questions is fine as well, as we don't have a public slack or discord for this (yet)! We will mention that as well in the documentation :)

**Comment by stephanembl** [comment]
Oops, I'll leave it open until we do remove it :D

**Comment by alexisvigoureux** [comment]
We have deleted it
